# Generated by Django 5.1.2 on 2024-11-05 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_vaccineschedule_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccineschedule',
            name='campaign',
        ),
    ]
