# Generated by Django 5.1.2 on 2024-11-05 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_remove_vaccineschedule_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccineschedule',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='campaign.campaign'),
            preserve_default=False,
        ),
    ]
