# Generated by Django 4.2.11 on 2024-11-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_vaccineschedule_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='image',
            field=models.ImageField(null=True, upload_to='campaign/images'),
        ),
    ]
