# Generated by Django 5.1.2 on 2024-11-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='role',
            field=models.CharField(default='Patient', editable=False, max_length=10),
        ),
    ]
