# Generated by Django 5.1.2 on 2024-11-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0002_vaccine_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='admin_route',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='available_doses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='side_effects',
            field=models.TextField(blank=True, null=True),
        ),
    ]
